title: Street Homeless Solutions Lab # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Street Homeless Solutions Lab is a new digital product and service design team within the Department of Homeless Services.
  <br><br>
  
  <a href="https://npstorey.github.io/SHSLab/about">About</a>
  <a href="https://npstorey.github.io/SHSLab/jobs">Jobs</a>
  <a href="https://npstorey.github.io/SHSLab/projects">Projects</a>
  <a href="https://npstorey.github.io/SHSLab/contact">Contact</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
