title: Street Homeless Solutions Lab # your name (or website title) here
logo: "/images/SHS_Lab_Logo_NoName.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Street Homeless Solutions Lab is a new digital product and service design team within the Department of Homeless Services.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
