title: Street Homeless Solutions Lab # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Street Homeless Solutions Lab is a new digital product and service design team within the Department of Homeless Services.
  <br>
  ### [About](/about.md)
  ### [Jobs](/jobs.md)
  ### [Projects](/projects.md)
  ### [Contact](/contact.md)
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
